version: '3'

services:
  events-api-service:
    image: adxl/bng-api-events:latest
    environment:
      STAGE: production
      DATABASE_URL: '@DATABASE_URL@'
    networks:
      - bng
      - default
    deploy:
      replicas: 3

  events-db-service:
    image: adxl/bng-db-events:latest
    environment:
      POSTGRES_USER: '@DB_USER@'
      POSTGRES_PASSWORD: '@DB_PASSWORD@'
      POSTGRES_DB: '@DB_NAME@'
    networks:
      - default
    deploy:
      replicas: 2

networks:
  default:
    driver: overlay
  bng:
    external: true
