version: '3'

services:
  events-api-services:
    image: adxl/bng-api-events:latest
    networks:
      - bng
      - default
    deploy:
      replicas: 3

  events-db-services:
    image: adxl/bng-db-events:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default
    deploy:
      replicas: 2

networks:
  default:
    driver: overlay
  bng:
    external: true

